defaults:
  - alg: rf_cls
  - _self_

llm:
  main_model: gpt-5-mini
  temperature: 1.0

dataset:
  _target_: utils.loader.Dataset
  model: gpt-4o-mini # Can be null if not using LLM-based annotations
  name: credit-g
  ratio: [0.4, 0.4, 0.2] # train, val, test

evaluator:
  n_data_splits: 5
  n_alg_runs: 3
  random_state: 0
  verbose: True

alg:
  param_grid:
    n_estimators: [50] # fixed for fair comparison
    max_depth: [3] # fixed for fair comparison

paths:
  project_root: .
  log_dir: ./logs
