name: CLASSIFICATION

on:
  workflow_dispatch:
    inputs:
      algorithm:
        description: "ALGORITHM"
        required: true
        default: "rf_cls"
        type: choice
        options:
          - rf_cls
          - et_cls
          - maple_cls

jobs:
  run:
    name: RUN | ${{ matrix.dataset }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dataset:
          - kr-vs-kp
          - letter
          - balance-scale
          - mfeat-factors
          - mfeat-fourier
          - mfeat-karhunen
          - mfeat-morphological
          - credit-g
          - diabetes
          - heart-statlog
          - liver
          - breast
          - vehicle
          - haberman
          - spambase
      fail-fast: false
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: CHECKOUT REPOSITORY
        uses: actions/checkout@v4

      - name: SETUP PYTHON
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: INSTALL DEPENDENCIES
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: RUN EVALUATION | ALGORITHM ${{ github.event.inputs.algorithm }} | DATASET ${{ matrix.dataset }}
        run: |
          python main.py \
                 alg=${{ github.event.inputs.algorithm }} \
                 dataset.name=${{ matrix.dataset }}
